CREATE TABLE IF NOT EXISTS signal_outcomes (
  id VARCHAR(36) PRIMARY KEY,
  user_id INT NULL,
  username VARCHAR(191) NULL,
  account_type ENUM('real', 'demo') NOT NULL DEFAULT 'real',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  asset VARCHAR(32) NOT NULL,
  technical_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
  news_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
  final_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
  recommendation VARCHAR(32) NOT NULL,
  confidence DECIMAL(10, 4) NOT NULL DEFAULT 0,
  market_regime VARCHAR(32) NOT NULL,
  action_taken VARCHAR(16) NOT NULL,
  requested_size DECIMAL(12, 4) NULL,
  adjusted_size DECIMAL(12, 4) NULL,
  guardrail_status VARCHAR(16) NOT NULL DEFAULT 'allowed',
  news_bias_1h DECIMAL(10, 4) NULL,
  current_btc_exposure_pct DECIMAL(10, 4) NULL,
  price_at_signal DECIMAL(20, 8) NULL,
  price_after_1h DECIMAL(20, 8) NULL,
  price_after_6h DECIMAL(20, 8) NULL,
  price_after_24h DECIMAL(20, 8) NULL,
  pnl_after_1h DECIMAL(12, 4) NULL,
  pnl_after_6h DECIMAL(12, 4) NULL,
  pnl_after_24h DECIMAL(12, 4) NULL,
  was_helpful_1h TINYINT(1) NULL,
  was_helpful_6h TINYINT(1) NULL,
  was_helpful_24h TINYINT(1) NULL,
  reasons_json JSON NULL,
  triggered_guardrails_json JSON NULL,
  INDEX idx_signal_outcomes_user_created (user_id, created_at),
  INDEX idx_signal_outcomes_username_created (username, created_at),
  INDEX idx_signal_outcomes_asset_created (asset, created_at),
  INDEX idx_signal_outcomes_account_created (account_type, created_at)
);
